name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get Information Variables
      id: core
      run: |
        echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    - name: Compile project
      run: |
        chmod +x build.sh
        mkdir vita-toolchain
        pwd
        ls
        sh build.sh
        pwd
        cd build
        make install DESTDIR=../vita-toolchain
    #- name: Upload artifacts
    #  if: ${{ success() }}
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: vita-toolchain-${{ steps.core.outputs.sha8 }}
    #    path: ./builds
