name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
    - uses: actions/checkout@v2

    - name: Get Information Variables
      id: core
      run: |
        echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    - name: Compile project
      run: |
        chmod +x build.sh
        pwd
        ls
        ./build.sh
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: vita-toolchain-${{ steps.core.outputs.sha8 }}
        path: ./builds
